[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
